spring.application.name=bankservice
server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankdb}
spring.datasource.username=${DB_USER:bankuser}
spring.datasource.password=${DB_PASSWORD:bankpass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.messages.basename=messages
spring.messages.encoding=UTF-8
logging.level.com.bankservice.auth=INFO


jwt.secret=${JWT_SECRET}
jwt.expiration=600000
jwt.refresh-expiration=120000

logging.level.org.springframework.security=DEBUG
aes.secret=${AES_SECRET}
crypto.secret-key=${CRYPTO_SECRET_KEY}


#부하측정
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

spring.datasource.hikari.maximum-pool-size=20
